name: Pipeline Minicurso
on:
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        node-version: 22
      - name: Setup environment variables
        run: |
          touch .env
          echo POSTGRESS_URL=${{ secret.POSTGRESS_URL }}
      - name: Run tests    
        run: |
          npm install
          npx prisma db push --force-reset
          npm run test:unit